### ISSUE TITLE
stop working. won't login at all  try everyone 

### ISSUE THREAD

**Issue by treforparr** [oznu/homebridge-gsh#41] opened 2020-04-25 08:27 UTC
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge GSH Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by oznu** [comment] 2020-04-26 06:08
Hi @treforparr,

Can you explain what you mean when you say "it won't login"?

**Comment by BobbySlope** [comment] 2020-04-26 18:34
hi @oznu this is an HOOBS user. We already tested this at his box and also other boxes.
The issue is when u linked an account with a device and setup a new device and want to link that, the process on your auth0 hangs and the gear icon is spinning endless

<img width="443" alt="Screenshot 2020-04-25 at 11 32 18" src="https://user-images.githubusercontent.com/50763727/80316260-1199f700-87fd-11ea-8995-ed04b91b2014.png">

its only happen after you successfully linked an device and setup an new one and you want to link that instead of the old one. relinking the old one works perfectly. 

is there an option to delete the current linking in the linking process?

**Comment by treforparr** [comment] 2020-05-04 00:23
I was hoping that there may be effects on this major problem with Google home,@oznu  really needs updating, authorisation is a major problem and I'm begging you to fix it in the nicest (possible way) please please please, had several ways to get it going and it just spins forever  the purple clock, it works fine with Home Bridge installation but not with hoobs,

**Comment by oznu** [comment] 2020-05-04 00:36
I can't replicate the issue in Homebridge Config UI X - which is what I support. HOOBS is using a fork of this plugin.

**Comment by oznu** [comment] 2020-05-04 00:36
See https://github.com/oznu/homebridge-gsh#configuration

> To configure homebridge-gsh you must also be running **homebridge-config-ui-x**.

**Comment by oznu** [comment] 2020-05-04 00:42
HOOBS is using https://github.com/hoobs-org/homebridge-google which has not included updates from this plugin since August 2019.

**Comment by treforparr** [comment] 2020-05-04 01:47
I have tried both and I still can’t get it to work

**Comment by donavanbecker** [comment] 2020-05-04 01:48
Then you should probably try homebridge and move away from HOOBs.

**Comment by treforparr** [comment] 2020-05-04 02:08
Don't really wanna change to Home Bridge as I've just spent £120 on a hoobs box, taking me ages just to to get it installed Home Bridge is too complex for me it's just the authorisation that needs fixing and brought up to date , Google recently released new updates that don't go in sync with the app it's like the ring if you don't keep that up-to-date it doesn't work)

**Comment by donavanbecker** [comment] 2020-05-04 02:20
Are you on homebridge discord server? If so reach out to me.

**Comment by treforparr** [comment] 2020-05-04 02:24
Yes I am I'm just wondering how do I find you on their

**Comment by BobbySlope** [comment] 2020-05-04 04:24
The issue with the gsh plugin is an server issue in the auth0 service and it happens also on homebridge not only on hoobs

We tested out the issue with gsh on hoobs and homebridge same behavior heres how to replicate:

Take raspberry 1, flash homebridge on it. Install gsh. Works perfect.

Now take raspberry 2, flash homebridge, install gsh. Try to link Auth0 hangs.

Reauth relink on raspberry 1 without issues

**Comment by AppleTechy** [comment] 2020-05-04 04:49
@treforparr Which authentication are you using? Github or Google?
@BobbySlope So is this issue only occurs on raspberry pi 2?

**Comment by BobbySlope** [comment] 2020-05-04 04:51
its Raspberry No1 and Raspberry No2 both Rpi Rpi3B

**Comment by BobbySlope** [comment] 2020-05-04 04:51
Both ways GitHub and google don't work

**Comment by AppleTechy** [comment] 2020-05-04 04:53
@BobbySlope That doesn't make sense? In your earlier comment you said that the first gen rpi works just fine?

**Comment by BobbySlope** [comment] 2020-05-04 04:53
@BobbySlope both are rpi3b

**Comment by oznu** [comment] 2020-05-04 04:55
I have just spun up HOOBS in a docker instance, you don't even have a link button?

![image](https://user-images.githubusercontent.com/3979615/80937134-37378980-8e17-11ea-8cae-96d8b4cdb10f.png)

**Comment by BobbySlope** [comment] 2020-05-04 04:56
@oznu Use the Certified one..... thats why we made a fork of it

**Comment by oznu** [comment] 2020-05-04 04:57
The certified one is from August 2019 and does not support short-form UUIDs, so will not work with the latest update anyway.

**Comment by BobbySlope** [comment] 2020-05-04 04:57
Its a bug in the Auth0 Server as I mentioned above @oznu you can try it out on two fresh flashed homebridge images on two separate devices

**Comment by BobbySlope** [comment] 2020-05-04 04:58
it works when u only link one device but when u try to switch to the second device it can't link anymore

**Comment by oznu** [comment] 2020-05-04 04:58
The plugin only supports running on a single device at a time:

https://github.com/oznu/homebridge-gsh#multiple-homebridge-instances

**Comment by BobbySlope** [comment] 2020-05-04 04:58
Yes even if you unlink it first

**Comment by oznu** [comment] 2020-05-04 05:00
I was able to link in the Docker image without issue.

![image](https://user-images.githubusercontent.com/3979615/80937318-f68c4000-8e17-11ea-9248-20addff43a84.png)

You are missing the "Unlink" button?

**Comment by BobbySlope** [comment] 2020-05-04 05:01
the second one also after unlinking in google home app?

**Comment by oznu** [comment] 2020-05-04 05:01
How are you unlinking the original instance?

**Comment by BobbySlope** [comment] 2020-05-04 05:01
delete the token and unlink in google home app

**Comment by oznu** [comment] 2020-05-04 05:02
So you're missing the unlink button.

![image](https://user-images.githubusercontent.com/3979615/80937395-41a65300-8e18-11ea-9487-b0ca48047a70.png)

**Comment by BobbySlope** [comment] 2020-05-04 05:02
the issue comes on the second device, not on the first device. you can relink the first device as much as you can

**Comment by oznu** [comment] 2020-05-04 05:04
I logged in with an account already in use by another instance and it worked find in the Docker image.

The plugin has had ~140 new users sign up in the last 7 days; only 2 HOOBS users have reported issues that I cannot replicate.

**Comment by BobbySlope** [comment] 2020-05-04 05:05
what if the user has no longer access to the old homebridge? and he can't unlink it with the button? this should be automated in the linking process. after auth unlink account if an account is already

**Comment by oznu** [comment] 2020-05-04 05:05
Then it won't be connected so he can re-link.

**Comment by BobbySlope** [comment] 2020-05-04 05:06
no he can't

**Comment by BobbySlope** [comment] 2020-05-04 05:07
neither can I on my test setup with two homebridge on two separate devices

**Comment by AppleTechy** [comment] 2020-05-04 05:12
I wasn't able to replicate . I used 2 different MacOS computers rather than RPI. But the issue should have still be replicable if it was an issue due to 2 seperate homebridge instances on 2 separate devices. 

**Steps to Reproduce**: 
1. Install Homebridge, Config-UI-X and hb service
2.  Install gsh plugin through Config-UI-X
3. Link Google account, restart homebridge
4. unlink account
5. Repeat steps 1-3 on secondary machine



**Environment**:

**Node.js Version**: 14.1.0
**NPM Version**: 6.14.4
**Homebridge Version**: v1.0.4
**Homebridge GSH Plugin Version**: v1.4.0
**Homebridge Config UI X Plugin Version**: v4.17.1
**Operating System**: MacOS Catalina (10.15.4)

**Comment by BobbySlope** [comment] 2020-05-04 05:22
I have unlinked the account by deleting the token in the ui, and unlink in google home app

**Comment by AppleTechy** [comment] 2020-05-04 05:40
Still wasn't able to reproduce. Second host was able to link on the homebridge side just fine and so was the Google Home app.

**Steps to Reproduce**: 
1. Install Homebridge, Config-UI-X and hb service
2.  Install gsh plugin through Config-UI-X
3. Link Google account, restart homebridge
4. unlink account via Config-UI-X GSH plugin unlink settings
5. unlink account in Google Home App
6. Shut down homebridge on this host
7. Force close Google Home App
5. Repeat steps 1-3 on secondary machine



**Environment**:

**Node.js Version**: 14.1.0
**NPM Version**: 6.14.4
**Homebridge Version**: v1.0.4
**Homebridge GSH Plugin Version**: v1.4.0
**Homebridge Config UI X Plugin Version**: v4.17.1
**Operating System**: MacOS Catalina (10.15.4)

**Comment by oznu** [comment] 2020-05-04 07:08
I still can't replicate this behaviour. Maybe you could make a video showing what's happening?

**Comment by oznu** [comment] 2020-05-04 10:02
@treforparr 

> I've just spent £120 on a hoobs box.

I am sorry about the situation you are in, and while I am not involved in HOOBS or ever received money from HOOBS for providing this service to their paying service customers, I will try and explain what is going on based on my research this afternoon.

---

I can see you connected today, so I'm guessing you obtained an auth token.

But you were probably either unable to add the action in the Google Home app, or the Google Home app kept on "unlinking" the action because the "Get Devices" request made to the plugin **was returning no devices**.

If you are running HOOBS 2.2.x then this is due to the changes introduced in the recent HAP-Nodejs update where by the "ID" numbers that HAP users to identify the device type changed. I fixed this issue before Homebridge 1.0.0 was released in this commit 16 days ago: https://github.com/oznu/homebridge-gsh/commit/ebbc0bf855054dee050a3cd5a7dbe1cc104c8c0f.

The current version of the plugin HOOBS lists as "certified" is not compatible with Homebridge 1.0.0 or HOOBS 2.2.x for this reason, as they have not incorporated any of the improvements and changes I have made to this plugin since August 2019 (this includes support for Security Systems, or two factor authentication).

It also seemed like you were connected via at least two instances at the same time? If you used a second instance to get an auth token, make sure you shut it down the other instance. Your account can only be linked to one Homebridge instance at a time otherwise you will encounter strange behaviour.

**Comment by oznu** [comment] 2020-05-04 10:12
Release notes for Homebridge GSH 1.4.0:

![image](https://user-images.githubusercontent.com/3979615/80955968-9c08d900-8e43-11ea-8d8e-d98f717140f6.png)

**Comment by oznu** [comment] 2020-05-04 10:34
Logs from server. I have obfuscated these to ensure your privacy.

May 04 12:56:22 - "HOMEBRIDGE" instance connects:

```
May 04 12:56:22 Client Connected: xxx.xxx.xx.xxx google-oauth2|xxxxxxxxxxxxxxxx HOMEBRIDGE_INSTANCE_898acd8a9cae07a8b3c82f4fa959564
```

May 04 13:27:09 - HOOBS connected:

```
May 04 13:27:09 Client Connected:  google-oauth2|xxxxxxxxxxxxxxxx HOOBS_INSTANCE__8092bc6b22b74085b599ce6410e46f7f8ce081d09d948cd76
```

At this point you now have two instances connected at the same time using the same account.

May 04 13:33:26  - You restart HOOBS a few times:

```
May 04 13:33:26 Client Disconnected: google-oauth2|xxxxxxxxxxxxxxxx HOOBS_INSTANCE__8092bc6b22b74085b599ce6410e46f7f8ce081d09d948cd76
May 04 13:33:33 Client Connected: google-oauth2|xxxxxxxxxxxxxxxx HOOBS_INSTANCE__8092bc6b22b74085b599ce6410e46f7f8ce081d09d948cd76
```

May 04 13:35:48 - Attempt to add the Homebridge action in the Google Home app:

```
May 04 13:35:48 action.devices.SYNC :: Request To google-oauth2|xxxxxxxxxxxxxxxx: {"body":{"inputs":[{"intent":"action.devices.SYNC"}],"requestId":"xxxxxxxxxxxxxxx"},"requestId":"xxxxxxxxxxxxxxxx"}
```

May 04 13:35:48 - The outdated GSH plugin responds with no device found:

```
May 04 13:35:48 action.devices.SYNC :: Response From google-oauth2|xxxxxxxxxxxxxxxx {"requestId":"xxxxxxxxxxxxxxx","payload":{"agentUserId":"google-oauth2|xxxxxxxxxxxxxxxx","devices":[]}}
```

The important part of this log line is:

```
"devices":[]
```

Now at this point you did have two instances connected, so both would get the SYNC request, but only one response would be accepted by the server, chances are because the HOOBS instance had no accessories to report (it couldn't find them due to the issues i mentioned in the comment above) - it responded first - and when Google receives an empty device list, it automatically unlinks the action.

I know this is a bit technical, but I hope it can help the HOOBS team resolve the problem for you.

**Comment by oznu** [comment] 2020-05-05 06:49
@treforparr - I'm closing this for now.

If you are still having issues I would recommend taking advantage of the HOOBS return policy.

> Returns are only accepted within 30 days from the date of purchase. To be eligible for a return, your item must be in the same condition that you received it. It must also be in the original packaging.

**Closed by oznu** 2020-05-05 06:49 UTC
Labels: bug
